### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jhngrant** [alphagov/maslow#294]
I'm looking for a tool to support user needs analysis in Wardley Mapping, and I would like to explore Maslow. Before doing so, it would be sensible to understand the license this repository is using. Can anyone confirm?

https://community.wardleymaps.com/t/a-potential-tool-to-capture-user-needs/120

**Comment by tijmenb** [comment]
Hi @jhngrant, I've added a license (MIT).

That said, I suspect it's unlikely that Maslow will suit your needs. It's a very specific tool that publishes the user need on the GOV.UK `/info` pages like https://www.gov.uk/info/benefits-calculators. It doesn't have many features besides the publishing.
